### 1. 查看店铺信息
GET http://localhost:8081/merchant/1

### 2. 浏览菜品列表
GET http://localhost:8081/dish/page?pageNum=1&pageSize=10&merchantId=1

### 3. 把水煮肉片加入购物车
POST http://localhost:8081/cart/add
Content-Type: application/json
X-Test-User-Id: 2

{"dishId": 4}

### 查看购物车
GET http://localhost:8081/cart/list
X-Test-User-Id: 2


### 5. 收藏这道菜
POST http://localhost:8081/favorite/4
X-Test-User-Id: 2

### 6. 新增收货地址
POST http://localhost:8081/address/add
Content-Type: application/json
X-Test-User-Id: 2

{
  "name": "张三",
  "phone": "13800138000",
  "address": "北京市海淀区中关村大街1号",
  "isDefault": 1
}

### 7. 查看我的地址
GET http://localhost:8081/address/list
X-Test-User-Id: 2

### 8.提交订单
POST http://localhost:8081/order/submit
Content-Type: application/json
X-Test-User-Id: 2

{
  "merchantId": 1,
  "addressId": 1,
  "totalPrice": 174.00,
  "itemList": [
    {
      "dishId": 4,
      "num": 3,
      "price": 58.00
    }
  ]
}

### 9. 查看我的订单列表
### 9. 查看我的订单列表
GET http://localhost:8081/order/userPage?pageNum=1&pageSize=10
X-Test-User-Id: 2

### 10. 查看购物车
GET http://localhost:8081/cart/list
X-Test-User-Id: 2

### 11. 模拟用户行为埋点
POST http://localhost:8081/behavior
Content-Type: application/json

{
  "userId": 2,
  "dishId": 5,
  "action": 1
}

### 12. 获取个性化推荐
GET http://localhost:8081/recommend/2

### 13. 获取全站热卖榜单
GET http://localhost:8081/recommend/hot
